// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiG195vH2vnDjlQc9zge4QaWEeYYINb5U',
    appId: '1:1097695538103:web:2f33520369c8538a3dd632',
    messagingSenderId: '1097695538103',
    projectId: 'fruits-hub-6d561',
    authDomain: 'fruits-hub-6d561.firebaseapp.com',
    storageBucket: 'fruits-hub-6d561.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfS0df3m24AJadScDEixnFzSidkWeF0R0',
    appId: '1:1097695538103:android:1f5b228c3b77d36c3dd632',
    messagingSenderId: '1097695538103',
    projectId: 'fruits-hub-6d561',
    storageBucket: 'fruits-hub-6d561.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4k8JygBht5oD-k53BQsm-C37PnFxxw78',
    appId: '1:1097695538103:ios:9bf4772f6bebda483dd632',
    messagingSenderId: '1097695538103',
    projectId: 'fruits-hub-6d561',
    storageBucket: 'fruits-hub-6d561.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4k8JygBht5oD-k53BQsm-C37PnFxxw78',
    appId: '1:1097695538103:ios:9bf4772f6bebda483dd632',
    messagingSenderId: '1097695538103',
    projectId: 'fruits-hub-6d561',
    storageBucket: 'fruits-hub-6d561.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiG195vH2vnDjlQc9zge4QaWEeYYINb5U',
    appId: '1:1097695538103:web:8dad376c57930a1b3dd632',
    messagingSenderId: '1097695538103',
    projectId: 'fruits-hub-6d561',
    authDomain: 'fruits-hub-6d561.firebaseapp.com',
    storageBucket: 'fruits-hub-6d561.firebasestorage.app',
  );
}
